### ISSUE TITLE
Mustache vs Handlebars

### ISSUE THREAD

**Issue by ConstantMath** [cjonasw/wordpress-starter-theme-mustache#1]
Hello, thanks for sharing this. We're using it on a project right now and working like this is way much cleaner.

I was just wondering if it was possible to use handlebars instead ?
Best,

**Comment by cjonasw** [comment]
Hey sorry for the late reply. 

Glad to hear it being used.

The idea with mustache is to completely separate logic from the view. Handlebars is a bit of a hybrid and requires JS to render the templates. I wouldn't mix the two, but if you need an on the fly renderer then Mustache has a JS renderer, along with many other languages: http://mustache.github.io/

I'm not sure how you would use Handlebars with Wordpress because it would be JS template rendering, but to be honest I would just use Timber+Twig, it's fantastic.
